# https://taskfile.dev

version: "3"

dotenv: [".env.task"]

vars:
  # This is wonky because both Taskfile and docker stats use Go text/template
  # {{`{{`}} is to produce a "{{" literal that will make it to docker stats
  DOCKER_STATS_FORMAT: "table {{`{{`}}.Name{{`}}`}}\t{{`{{`}}.Container{{`}}`}}\t{{`{{`}}.CPUPerc{{`}}`}}\t{{`{{`}}.MemUsage{{`}}`}}\t{{`{{`}}.MemPerc{{`}}`}}"
  DEV_POSTGRES_CONTAINER: "davidharting-dev-postgres"

tasks:
  format:
    desc: "Format all backend and frontend code"
    cmds:
      - ./vendor/bin/pint
      - npm run format

  dev:db:refresh:
    desc: "Migrate fresh and re-seed"
    cmds:
      - php artisan migrate:fresh
      - php artisan db:seed

  dev:preflight:
    desc: "Check that all development dependencies are available"
    cmd: ./scripts/preflight-check.sh

  dev:db:start:
    desc: "Start a standalone Postgres container for local development"
    cmds:
      - ./scripts/start-dev-postgres.sh

  dev:db:stop:
    desc: "Stop the standalone Postgres development container"
    cmd: ./scripts/stop-dev-postgres.sh

  dev:install:
    desc: "Install PHP and Node dependencies"
    cmds:
      - composer install
      - npm install

  dev:serve:
    desc: "Start local development environment (Postgres, web server, Vite, queue worker)"
    deps:
      - dev:preflight
      - dev:install
    vars:
      DB_PORT:
        sh: ./scripts/start-dev-postgres.sh
    env:
      DB_HOST: "127.0.0.1"
      DB_PORT: "{{.DB_PORT}}"
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      DB_DATABASE: "laravel"
    cmds:
      - echo "Postgres running on port {{.DB_PORT}}"
      - php artisan migrate:fresh --seed
      - defer: { task: dev:db:stop }
      - cmd: |
          trap 'kill 0' EXIT
          php artisan serve &
          npm run dev &
          php artisan queue:work --tries=3 &
          wait

  dev:docker:build:
    desc: "Builds the image containing Frankenphp and the Laravel app"
    cmd: docker builder build -t davidhartingdotcom:latest -f Dockerfile .

  dev:docker:up:
    desc: "Bring up all services with docker-compose using development configuration"
    cmd: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
    deps:
      - dev:docker:down
      - dev:docker:build

  dev:docker:down:
    desc: "Bring down all docker-compose services"
    cmd: docker-compose down -v

  docker:stats:
    desc: "Monitor CPU and memory usage of docker-compose services"
    cmd: docker stats --no-stream --format '{{.DOCKER_STATS_FORMAT}}'

  prod:build:
    desc: "Build docker image for production deployment"
    vars:
      TAG: '{{.TAG | default "latest"}}'
      IMAGE_NAME: "davidhartingdotcom:{{.TAG}}"
      TAR_FILE: "davidhartingdotcom-{{.TAG}}.tar"
    cmds:
      - docker buildx build --platform linux/amd64 -t {{.IMAGE_NAME}} -f Dockerfile .
      - docker save --output {{.TAR_FILE}} {{.IMAGE_NAME}}
      - echo "Build complete! Tar file saved as {{.TAR_FILE}}"

  prod:deploy:
    desc: "Deploy latest docker image to production server"
    cmds:
      - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/$SSH_USER/repos/davidharting.com && docker pull ghcr.io/davidharting/davidharting.com:latest && docker compose up -d"
      - echo "Deploy complete!"

  prod:ssh:shell:
    desc: "Open an interactive SSH shell on the production server"
    cmd: ssh -t -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/$SSH_USER/repos/davidharting.com && exec bash"

  prod:ssh:exec:
    desc: "Execute a command on the production server (usage: task prod:ssh:exec -- <command>)"
    cmd: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/$SSH_USER/repos/davidharting.com && {{.CLI_ARGS}}"

  prod:web:exec:
    desc: "Execute a command in the production web container with secrets loaded (usage: task prod:web:exec -- <command>)"
    cmd: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/$SSH_USER/repos/davidharting.com && docker compose exec -T web bash /entrypoint.sh {{.CLI_ARGS}}"

  prod:web:shell:
    desc: "Open an interactive shell in the production web container with secrets loaded"
    cmd: ssh -t -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/$SSH_USER/repos/davidharting.com && docker compose exec web bash /entrypoint.sh bash"
