name = "davids-site"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [ 
  { binding = "SECRET_MESSAGES", id = "377b42faf5df4671922ff025f0dc64e1" }
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"