name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-via-dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.8.x
          cache: npm
      - name: Install npm dependencies
        run: npm install
      - name: Deploy with Dagger
        run: node ace pipeline:deploy
